### ISSUE TITLE
[Bug] Spread operator in styleguide configuration

### ISSUE THREAD

**Issue by tomitrescak** [hallister/semantic-react#58]
Hi. Tried to do npm install and npm ....

But am getting this error:

```
► npm run styleguide-server

> semantic-react@0.0.2 styleguide-server /Users/tomi/Downloads/semantic-react-master
> styleguidist server

/Users/tomi/Downloads/semantic-react-master/styleguide.config.js:45
        webpackConfig.resolveLoader.modulesDirectories = ['src/loaders', ...webpackConfig.resolveLoader.modulesDirectories];
                                                                         ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at readConfig (/Users/tomi/Downloads/semantic-react-master/node_modules/react-styleguidist/src/utils/config.js:54:16)
    at Object.<anonymous> (/Users/tomi/Downloads/semantic-react-master/node_modules/react-styleguidist/src/utils/config.js:202:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tomi/Downloads/semantic-react-master/node_modules/react-styleguidist/src/make-webpack-config.js:6:14)
```

**Comment by tomitrescak** [comment]
Looks like you are using a destructuring operator in that JS file. What version of node are you using? Even 5.9 does not have destructuring available.

**Comment by asvetliakov** [comment]
It's spread operator, should work on node 5.0+ without any flags, but you're right, it shouldn't be here
